version: "3"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: daniel
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./db/sql-scripts/CreateTables.sql:/docker-entrypoint-initdb.d/1.sql
    cap_add:
      - SYS_NICE

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    depends_on:
      - db

  web:
    build: ../
    ports:
      - "3001:3000"
    depends_on:
      - db
    volumes:
      - ../:/usr/src/app
      - /usr/src/app/node_modules
